#!/usr/bin/env bash
# fleet-sync-config.sh — Sync fleet machine configs to local-studio-controllers.json.
#
# Reads the fleet-overnight status API + generates the controllers config file
# that the dashboard telemetry route uses to probe local-studio controllers.
#
# Usage: fleet-sync-config.sh [--output <path>] [--api-key <key>]
#
# Output defaults to ~/.openclaw/local-studio-controllers.json
set -euo pipefail

OUTPUT="${HOME}/.openclaw/local-studio-controllers.json"
API_KEY=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --output) OUTPUT="$2"; shift 2 ;;
    --api-key) API_KEY="$2"; shift 2 ;;
    *) shift ;;
  esac
done

API_URL="http://127.0.0.1:3007/api/fleet-overnight/status"

echo "Syncing fleet config from $API_URL → $OUTPUT"

curl -sf -m 10 "$API_URL" 2>/dev/null | python3 -c "
import json, sys

d = json.load(sys.stdin)
controllers = []
for m in d.get('machines', []):
    if m.get('status') != 'online':
        continue
    host = m.get('host', '')
    if not host:
        continue
    entry = {
        'name': m.get('id', ''),
        'url': f'http://{host}:8080',
    }
    api_key = sys.argv[1] if len(sys.argv) > 1 and sys.argv[1] else ''
    if api_key:
        entry['apiKey'] = api_key
    controllers.append(entry)

config = {
    '_comment': 'Auto-generated by fleet-sync-config.sh from the fleet-overnight status API. Controllers are NOT yet deployed — telemetry route returns reachable=false until local-studio is installed on each box.',
    'controllers': controllers,
}

with open(sys.argv[2] if len(sys.argv) > 2 and sys.argv[2] else '/dev/stdout', 'w') as f:
    json.dump(config, f, indent=2)
    f.write('\n')

print(f'Wrote {len(controllers)} controllers', file=sys.stderr)
" "$API_KEY" "$OUTPUT" 2>&1

echo "Done. Controllers config: $OUTPUT"
